<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-VB21DVG" ignored="0" name="FirefoxTest" tests="1" failures="1" timestamp="19 Aug 2019 05:32:53 GMT" time="29.379" errors="0">
  <testcase name="Login" time="4.985" classname="Runner.MasterRunner">
    <failure type="org.testng.TestException" message="
Error in sending to the following element: ">
      <![CDATA[org.testng.TestException: 
Error in sending to the following element: 
at Utils.Action.sendKeys(Action.java:158)
at Testcase.Login.LoginFunction.Login2(LoginFunction.java:44)
at Runner.MasterRunner.Login(MasterRunner.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Login -->
</testsuite> <!-- FirefoxTest -->
